name: Automated Multi-Container Deployment

on:
  push:
    branches:
      - main
    paths:
      - '01-docker-static-web/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Download the code from GitHub's servers onto the runner
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # SSH into your EC2 Instance and execute commands
      - name: Deploy Stack to AWS EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p ~/web-app
            cd ~/web-app
            rm -rf * .git .github
            git clone https://github.com/FFreezed/dummy-static-web .
            cd 01-static-web
            sudo docker-compose up --build -d
            sudo docker system prune -f